# All paths are relative to main.py.

data:
  # data node passed to user-defined _data_load function
  # n_df = num. of DataFrames for data_load to return. None => all DataFrames.
  n_df: null
  data_directory: ./data/raw/satellite-b
  satellites:
    - cluster1
    - cluster2
    - cluster3
    - cluster4
    - geotail
    - goes8
    - goes9
    - goes10
    - goes12
    - imp8
    - polar
    - rbspa
    - rbspa
    - themisa
    - themisb
    - themisc
    - themisd
    - themise

# User-defined script for loading data. Must contain a function job_list(config)
job_script: ./configs/satellite-b/job_script.py

tag: null
parallel_jobs: true

results_dir: ./data/results/satellite-b/results-4
results_desc: Same as results-1 but using new code structure and computing _resid models

# device sets training parallelization using one of
#   null
#   cpu (default if device is null)
#   gpu (Linux/Windows)
#   mps (OS-X)
device: null

dtype: float32

num_epochs: 50
num_boot_reps: 1
batch_size: 256
hidden_size: 32
activation: Tanh
optimizer: Adam
optimizer_kwargs:
  lr: 0.01

# True => [None, **outputs]; null or no attribute => Only use all inputs
removed_inputs: true

models:
  - ols
  - nn_mimo
  - nn_mimo_resid
  - nn_miso
  - nn_miso_resid

inputs: [r, theta, phi, imfby, imfbz, vsw, nsw, ey, ey_avg]
outputs: [bx, by, bz]
