base_config: ./configs/satellite-b/base.yaml
run_dir: ./data/results/satellite-b/test-parallel
run_desc: Test run
data:
  satellites:
    - cluster1
    - cluster2
  n_df: 2
parallel_jobs: false
num_epochs: 5
num_boot_reps: 1
# removed_inputs: [null, r]
removed_inputs:
  - null
