base_config: ./configs/satellite-b/base.yaml
run_dir: ./data/results/satellite-b/results-0-serial
run_desc: Test run
data:
  satellites:
    - cluster1
  n_df: 2
parallel_jobs: false
device: mps
num_epochs: 1
num_boot_reps: 2
# removed_inputs: [null, r]
removed_inputs:
  - null
