# All paths are relative to main.py.

# User-defined script for loading data. Must contain a function job_list(config)
job_script: ./configs/demo/job_script.py

data:

# job name below is set in job_script.py
job: null

parallel_jobs: true

run_dir: ./data/results/demo/results-0
run_desc: Same as results-1 but using new code structure and computing _resid models

# device sets training parallelization using one of
#   null
#   cpu (default if device is null)
#   gpu (Linux/Windows)
#   mps (OS-X)
device: null

# True => [None, **outputs]; null or no attribute => Only use all inputs
removed_inputs: true

models:
  - ols
  - nn_mimo
  - nn_mimo_resid
  - nn_miso
  - nn_miso_resid

inputs: [r, theta, phi, imfby, imfbz, vsw, nsw, ey, ey_avg]
outputs: [bx, by, bz]

dtype: float32

train_fraction: 0.8

# Neural network hyperparameters
num_epochs: 50
num_boot_reps: 1
batch_size: 256
hidden_size: 32
activation: Tanh
optimizer: Adam
optimizer_kwargs:
  lr: 0.01
