# All paths are relative to main.py.

# User-defined script for loading data. Must contain a function job_list(config)
job_script: ./configs/demo/job_script.py

data:
  noise_amplitude: 0.1
  cadence: 1s
  start: 2023-01-01
  end: 2023-01-02

# job name below is set in job_script.py
job: null

parallel_jobs: true

run_dir: ./data/results/demo/demo-0
run_desc: Description of demo-0 run
